# This is a basic workflow to help you get started with Actions

name: GradlewBuildCl

on:
  push:
    branches: [ master, experimental ]
  pull_request:
    branches: [ master, experimental ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run gradlew build
      run: |
        echo building project...
        ./gradlew build
